services:
  backend:
    build: ./backend
    volumes:
      - ./backend/models:/app/models
      - ./backend/faiss:/app/faiss
      - ./backend/queues:/app/queues
    networks:
      - analysis-net
    depends_on:
      - dask-scheduler
    environment:
      - ACTIVE_MODEL=v1
      - PYTHONUNBUFFERED=1
    container_name: backend-chat-analysis
    hostname: backend

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "881:3000"
    networks:
      - analysis-net
      - nginx-proxy_default
    container_name: frontend-chat-analysis
    hostname: frontend

  dask-scheduler:
    image: daskdev/dask:latest
    command: dask-scheduler
    networks:
      - analysis-net
    container_name: dask-scheduler
    hostname: dask-scheduler

  dask-worker:
    image: daskdev/dask:latest
    command: dask-worker dask-scheduler:8786
    deploy:
      replicas: 2
    networks:
      - analysis-net

networks:
  analysis-net:
    driver: bridge
  nginx-proxy_default:
    external: true
