services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${VITE_API_URL:-/api} # Changed from REACT_APP_API_URL
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - analysis-net
      - nginx-proxy_default
    container_name: frontend
    hostname: frontend

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - analysis-net
    container_name: rabbitmq
    hostname: rabbitmq

  dask-scheduler:
    image: ghcr.io/dask/dask:latest
    command: ["dask", "scheduler"]
    ports:
      - "8786"
      - "8787" # Dashboard port
    networks:
      - analysis-net
    container_name: scheduler
    hostname: scheduler

  dask-worker:
    image: ghcr.io/dask/dask:latest
    command: ["dask", "worker", "tcp://scheduler:8786"]
    environment:
      - DASK_SCHEDULER=tcp://scheduler:8786
    depends_on:
      - dask-scheduler
    networks:
      - analysis-net
    deploy:
      replicas: ${DASK_WORKERS:-2}

  db:
    image: ${DB_IMAGE:-mariadb:10.6}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_DATABASE:-ai3_auth}
      - MYSQL_USER=${DB_USERNAME:-ai3user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-ai3password}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - analysis-net
    container_name: db
    hostname: db
    # Only create this service in production or when explicitly requested
    profiles:
      - production
      - mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - faiss_data:/app/faiss
      - uploads_data:/app/uploads
      - models_data:/app/models
      - db_data:/app/db # For SQLite persistence
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-development_secret_key}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672/
      - DASK_SCHEDULER=tcp://scheduler:8786
      # Database configuration
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_PATH=/app/db/auth.db
      # MySQL configuration (used when DB_TYPE=mysql)
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-ai3user}
      - DB_PASSWORD=${DB_PASSWORD:-ai3password}
      - DB_DATABASE=${DB_DATABASE:-ai3_auth}
      - DB_POOL_SIZE=${DB_POOL_SIZE:-10}
      - DB_MAX_OVERFLOW=${DB_MAX_OVERFLOW:-20}
      - DB_POOL_RECYCLE=${DB_POOL_RECYCLE:-3600}
    depends_on:
      - rabbitmq
      - dask-scheduler
    networks:
      - analysis-net
    container_name: backend
    hostname: backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "881:80" # Never change this port
    depends_on:
      - frontend
      - backend
      - rabbitmq
      - dask-scheduler
    networks:
      - analysis-net
      - nginx-proxy_default
    container_name: chat-analysis
    hostname: chat-analysis
    environment:
      # - VIRTUAL_HOST=${VIRTUAL_HOST:-ai1.home}
      # - VIRTUAL_PORT=80
      - SERVER_NAME=${SERVER_NAME:-ai1.home}

networks:
  analysis-net:
    driver: bridge
  nginx-proxy_default:
    external: true

volumes:
  rabbitmq_data:
    driver: local
  faiss_data:
    driver: local
  uploads_data:
    driver: local
  models_data:
    driver: local
  db_data:
    driver: local
